Introduce version constraint for rest-client gem
rest-client 1.7.3 drops monkey patch on MIME::Types causing NoMethodError during Logux::Client#post execution ("undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>").

See also: https://github.com/rest-client/rest-client/blob/c469b3629ca826dac77416fc39adce190cde2a82/history.md#173